# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

---

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

---

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

---

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

---

### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

---

### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

---

### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

---

### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

---

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---


In [2]:
# Question 1
import numpy as np
array = np.arange(1,11)
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# Question 2
zeros_array = np.zeros((3, 3))
print(zeros_array)



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
#Question 3

np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [5]:
# Question 4
identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
#Question 5

random_matrix = np.random.rand(4, 4)
print(random_matrix)


[[0.00369472 0.00464189 0.73433998 0.19371325]
 [0.3682651  0.03258777 0.91890692 0.01645075]
 [0.01963382 0.77292226 0.20542224 0.33687316]
 [0.39430677 0.30298078 0.16172806 0.01261961]]


In [16]:
# Question 6
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_shape = array.shape
print(array_shape)



(3, 3)


In [20]:
# Question 7
array = np.arange(1,17)
b=array.reshape(4,4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [21]:
#Question 7 second approach

array = np.arange(1,17).reshape(4,4)
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [22]:
#Question 8
d = np.array([[1, 2, 3],[2, 4, 11,],[7,5,1]])
print(d.dtype)


int32


In [29]:
# Question 9
a = np.arange(1,101)
b = a[a % 2 == 0]
print(b)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [36]:
#Question 9 using for loop
for i in range(1, 101):
    if i % 2 == 0:
        print(i, end = ",")

2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,90,92,94,96,98,100,

In [74]:
#Question 10

array = np.random.randint(10, 50, size = (6,6))
print(array)

[[48 37 26 43 18 28]
 [21 41 29 16 27 49]
 [25 16 29 23 10 32]
 [18 44 49 31 16 25]
 [21 22 25 38 20 20]
 [13 34 35 30 43 35]]


In [61]:
#Question 11
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

submatrix = array[0:2, 1:3]

print(submatrix)




[[2 3]
 [6 7]]


In [64]:
# Question 12
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
total_sum = np.sum(array)
print("Sum of all elements:", total_sum)



Sum of all elements: 55


In [63]:
# Question 13
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mean_value = np.mean(array)
median_value = np.median(array)
std_deviation = np.std(array)
print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_deviation)


Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143


In [76]:
#Question 14
maximum_and_minimum_values = np.array([1, 2, 3, 4, 5])
a = np.max(maximum_and_minimum_values)
b = np.min(maximum_and_minimum_values)
print("Maximum value:", a)
print("Minimum value:", b)


Maximum value: 5
Minimum value: 1


In [77]:
#Question 15
random_integers = np.random.randint(1, 101, 20)
index_of_max = np.argmax(random_integers)
print("Array of random integers:", random_integers)
print("Index of the maximum value:", index_of_max)


Array of random integers: [10 86 83 82 48 44 49 37 70 46 78 29 90  2 88 77 66 70 21  8]
Index of the maximum value: 12


In [78]:
# Question 16
array = np.array([1, 2, 3, 4, 5])
reversed_array = array[::-1]
print("Original array:", array)
print("Reversed array:", reversed_array)


Original array: [1 2 3 4 5]
Reversed array: [5 4 3 2 1]


In [81]:
#Question 17
matrix_a = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

matrix_b = np.array([[9, 8, 7],
                      [6, 5, 4],
                      [3, 2, 1]])
result = matrix_a * matrix_b
print("\nResult of element-wise multiplication:")
print(result)




Result of element-wise multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [83]:
# Question 18
array = np.array([1, 2, 3, 4, 5])
diagonal_matrix = np.diag(array)
print("\nDiagonal Matrix:")
print(diagonal_matrix)



Diagonal Matrix:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [86]:
#Question 19
matrix_a = np.array([[1, 2, 3],
                      [4, 5, 6]])

matrix_b = np.array([[7, 8],
                      [9, 10],
                      [11, 12]])

result_dot = np.dot(matrix_a, matrix_b)
result_at = matrix_a @ matrix_b
print("\nResult of matrix multiplication (using np.dot):")
print(result_dot)





Result of matrix multiplication (using np.dot):
[[ 58  64]
 [139 154]]


In [89]:
# Question 20

import numpy as np
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

flattened_array = array_2d.flatten()
print("\nFlattened 1D Array:")
print(flattened_array)



Flattened 1D Array:
[1 2 3 4 5 6 7 8 9]
